<?php

namespace Seko;

class DangerousGoodsEnum
{
	const __default = 'UNKNOWN';
	const UNKNOWN = 'UNKNOWN';
	const INACCESSIBLE = 'INACCESSIBLE';
	const ACCESSIBLE = 'ACCESSIBLE';
	const EXCEPTED_QUANTITIES = 'EXCEPTED_QUANTITIES';
	const FULLY_REGULATED = 'FULLY_REGULATED';
	const LITHIUM_BATTERIES = 'LITHIUM_BATTERIES';
	const BIOLOGICAL_SUBSTANCE_UN_3373 = 'BIOLOGICAL_SUBSTANCE_UN_3373';
	const LIMITED_QUANTITIES = 'LIMITED_QUANTITIES';


}
